version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - users_auth_boilerplate_db:/var/lib/postgresql/data
volumes:
  users_auth_boilerplate_db:
    driver: local
